// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: microService.proto

package micro

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MicroServiceClient is the client API for MicroService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MicroServiceClient interface {
	GeneralCall(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error)
}

type microServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMicroServiceClient(cc grpc.ClientConnInterface) MicroServiceClient {
	return &microServiceClient{cc}
}

func (c *microServiceClient) GeneralCall(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/micro.MicroService/generalCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MicroServiceServer is the server API for MicroService service.
// All implementations should embed UnimplementedMicroServiceServer
// for forward compatibility
type MicroServiceServer interface {
	GeneralCall(context.Context, *RequestMessage) (*ResponseMessage, error)
}

// UnimplementedMicroServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMicroServiceServer struct {
}

func (UnimplementedMicroServiceServer) GeneralCall(context.Context, *RequestMessage) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneralCall not implemented")
}

// UnsafeMicroServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MicroServiceServer will
// result in compilation errors.
type UnsafeMicroServiceServer interface {
	mustEmbedUnimplementedMicroServiceServer()
}

func RegisterMicroServiceServer(s grpc.ServiceRegistrar, srv MicroServiceServer) {
	s.RegisterService(&MicroService_ServiceDesc, srv)
}

func _MicroService_GeneralCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MicroServiceServer).GeneralCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/micro.MicroService/generalCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MicroServiceServer).GeneralCall(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// MicroService_ServiceDesc is the grpc.ServiceDesc for MicroService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MicroService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "micro.MicroService",
	HandlerType: (*MicroServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "generalCall",
			Handler:    _MicroService_GeneralCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "microService.proto",
}
